default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: backend_development
  host: <%= Rails.application.credentials.development[:pg][:host] %>
  username: <%= Rails.application.credentials.development[:pg][:user] %>
  port: <%= Rails.application.credentials.development[:pg][:port] %>

test:
  <<: *default
  database: backend_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  port: <%= Rails.application.credentials.production[:pg][:port] %>
  host: <%= Rails.application.credentials.production[:pg][:host] %>
  username: <%= Rails.application.credentials.production[:pg][:user] %>
  password: <%= Rails.application.credentials.production[:pg][:password] %>
  database: <%= Rails.application.credentials.production[:pg][:database] %>
